### ISSUE TITLE
Bad HTTP redirects for tools

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/rfcdiff#10]
### Describe the issue

I'm not sure if this is a "Datatracker" bug per se, but:

`https://tools.ietf.org/tools/rfcdiff/rfcdiff-1.46.tgz` redirects to `https://author-tools.ietf.org/iddiff/rfcdiff-1.46.tgz`. However, the latter redirects to `https://_/iddiff`, which is clearly wrong.

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by paulehoffman** [comment]
> [@paulehoffman](https://github.com/paulehoffman), where do you find that reference to `rfcdiff-1.46.tgz`?

It appears in Lars Eggert's Homebrew cask for rfcdiff.

**Comment by kesara** [comment]
I can't find any custom casks, and looks like rfcdiff has been removed from homebrew-core.

**Comment by kesara** [comment]
I have created a release for the [1.48](https://github.com/ietf-tools/rfcdiff/releases/tag/1.48).
May be we could get any package managers to use the new location.

**Comment by cabo** [comment]
Thanks.  I have alerted Lars.

https://github.com/larseggert/homebrew-mytap/issues/1

Grüße, Carsten
