### ISSUE TITLE
Update or remove project URL in diff results

### ISSUE THREAD

**Issue by kesara** [ietf-tools/rfcdiff#5]
`rfcdiff` adds a link to `http://www.tools.ietf.org/tools/rfcdiff/` in diff results. 
This should be updated or removed.

Reference:
* https://github.com/ietf-tools/author-tools/issues/487

**Comment by rjsparks** [comment]
It also has links to documents going through www.tools.ietf.org redirects that should be aimed directly at documents instead.

**Comment by kesara** [comment]
Fixed with #7
